
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend"
    assignees:
      - "thoomasbro"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/datascience"
    assignees:
      - "thoomasbro"
    schedule:
      interval: "monthly"
    # Disable all dependencies update
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 0
  
  - package-ecosystem: "npm"
    directory: "/frontend"
    assignees:
      - "thoomasbro"
      - "claire2212"
    schedule:
      interval: "weekly"
