version: 2
rebase-strategy: "disabled"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 30
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 30
    assignees:
      - "claire2212"
      - "maximeperraultdev"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: [ "tech. enhancement", "dependencies" ]

  - package-ecosystem: "gradle"
    directory: "/backend"
    cooldown:
      default-days: 30
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 30
    assignees:
      - "maximeperraultdev"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: [ "tech. enhancement", "dependencies" ]
    groups:
      non-major-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: [ "minor", "patch" ]
      non-major-dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: [ "minor", "patch" ]

  - package-ecosystem: "pip"
    cooldown:
      default-days: 30
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 30
    directory: "/pipeline"
    exclude-paths:
      - "pipeline/poetry.lock"
    assignees:
      - "VincentAntoine"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: [ "tech. enhancement", "dependencies" ]
    groups:
      non-major-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: [ "minor", "patch" ]
      non-major-dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: [ "minor", "patch" ]

  - package-ecosystem: "npm"
    cooldown:
      default-days: 30
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 30
    directory: "/frontend"
    exclude-paths:
      - "frontend/package-lock.json"
    assignees:
      - "claire2212"
      - "maximeperraultdev"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: [ "tech. enhancement", "dependencies" ]
    ignore:
      - dependency-name: "rsuite"
    groups:
      non-major-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: [ "minor", "patch" ]
      non-major-dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: [ "minor", "patch" ]
