env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  describe: readonly
  it: readonly
  expect: readonly
  jest: readonly
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
rules: {
  "react-hooks/exhaustive-deps": "warn",
  "react/prop-types": "off",
  "react-hooks/rules-of-hooks": "error",
  "no-shadow": ["warn", { "builtinGlobals": false, "hoist": "functions", "allow": ["resolve", "reject", "done"] }],
  "block-scoped-var": "warn",
  "consistent-return": "warn",
  "react/forbid-component-props": "warn",
  "react/forbid-dom-props": "warn",
  "react/no-access-state-in-setstate": "warn",
  "react/no-array-index-key": "warn",
  "react/jsx-no-bind": "warn"

}
settings:
  react:
    version: 16.13.1
