SELECT
  id,
  st_multi(ST_SimplifyPreserveTopology(ST_CurveToLine(geom), 0.00001)) geom,
  url,        
  layer_name,
  facade,
  ref_reg,
  creation,
  edition_bo,
  edition_cacem,
  editeur,
  source,
  observation,
  thematique,
  date,
  duree_validite,
  date_fin,
  temporalite,
  type,
  resume,
  poly_name,
  plan,
  authorization_periods,
  prohibition_periods,
  others_ref_reg
FROM public.regulatory_areas;