export enum BackOfficeConfirmationModalActionType {
  'ARCHIVE_ADMINISTRATION' = 'ARCHIVE_ADMINISTRATION',
  'ARCHIVE_CONTROL_UNIT' = 'ARCHIVE_CONTROL_UNIT',
  'DELETE_ADMINISTRATION' = 'DELETE_ADMINISTRATION',
  'DELETE_CONTROL_UNIT' = 'DELETE_CONTROL_UNIT'
}
