SELECT
    m.ID_FMC_BC_MISSION AS mission_id,
    mu.IDC_FMC_MOYEN_CONTROLE AS control_unit_id
FROM FMC2.FMC_BC_MISSION m
JOIN FMC2.FMC_BC_MISSION_UNITE mu
ON m.ID_FMC_BC_MISSION = mu.ID_FMC_BC_MISSION
WHERE m.DATE_DEBUT_MISSION < TO_DATE( '2023-01-01', 'YYYY-MM-DD')
