SELECT
FMC2.FMC_BC_MISSION.ID_FMC_BC_MISSION AS id,
CASE
    WHEN FMC2.FMC_CODE_TYPE_CONTROLE.LIBELLE_COURT='Au port' THEN 'LAND'
    WHEN FMC2.FMC_CODE_TYPE_CONTROLE.LIBELLE_COURT='En mer' THEN 'SEA'
    WHEN FMC2.FMC_CODE_TYPE_CONTROLE.LIBELLE_COURT='Aérien' THEN 'AIR'
END AS mission_type,
FMC2.FMC_BC_MISSION.TRIGRAMME_UTILISATEUR_SAISIE AS open_by,
FMC2.FMC_BC_MISSION.OBSERVATIONS as observations_cacem,
FMC2.FMC_CODE_PLAN_FACADE.LIBELLE as facade,
FMC2.FMC_BC_MISSION.DATE_DEBUT_MISSION as start_datetime_utc,
FMC2.FMC_BC_MISSION.DATE_FIN_MISSION as end_datetime_utc,
FMC2.FMC_BC_MISSION.TRIGRAMME_UTILISATEUR_CLOTURE AS closed_by,
'POSEIDON_CACEM' AS mission_source,
FMC2.FMC_BC_MISSION.CLOTURER as closed


FROM FMC2.FMC_BC_MISSION

LEFT JOIN FMC2.FMC_CODE_TYPE_CONTROLE
ON FMC2.FMC_BC_MISSION.IDC_FMC_TYPE_MISSION=FMC2.FMC_CODE_TYPE_CONTROLE.IDC_FMC_TYPE_CONTROLE

LEFT JOIN FMC2.FMC_CODE_PLAN_FACADE
ON FMC2.FMC_BC_MISSION.IDC_FMC_PLAN_FACADE=FMC2.FMC_CODE_PLAN_FACADE.IDC_FMC_PLAN_FACADE
