services:
  db:
    volumes:
      - "../../.backups/:/opt/monitorenv_backups"

  monitorfish:
    image: rodolpheche/wiremock
    ports:
      - 8082:8080
    volumes:
      - ../../frontend/cypress/mappings/monitorfish:/home/wiremock/mappings
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/api/v1/mission_actions?missionId=34 || exit 1 "]
      interval: 1s
      timeout: 1s
      retries: 30
