version: '3'
services:
  db:
    image: timescale/timescaledb-postgis:1.7.4-pg11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  geoserver:
    image: kartoza/geoserver:2.20.2
    restart: unless-stopped
    environment:
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
    ports:
      - ${GEOSERVER_PORT}:8080
    links:
      - "db:db"
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - geoserver-settings:/settings
    depends_on:
      - db
    # healthcheck:
    #   test: curl --fail -s http://localhost:8080/geoserver/index.html || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3

volumes:
  geoserver-data:
    driver: local
  geoserver-settings:
    driver: local
  db-data:
    driver: local
