services:
  db:
    volumes:
      - "../../.backups/:/opt/monitorenv_backups"

  monitorfish:
    image: rodolpheche/wiremock
    ports:
      - 8082:8080
    volumes:
      - ../../frontend/cypress/mappings/monitorfish:/home/wiremock/mappings
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/api/v1/mission_actions?missionId=34 || exit 1 "]
      interval: 1s
      timeout: 1s
      retries: 30

  rapportnav:
    image: rodolpheche/wiremock
    ports:
      - 8083:8080
    volumes:
      - ../../frontend/cypress/mappings/rapportnav:/home/wiremock/mappings
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/api/v1/missions/34 || exit 1 "]
      interval: 1s
      timeout: 1s
      retries: 30

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8085:8080"
    volumes:
      - ../configurations/keycloack:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
