services:
  db:
    image: timescale/timescaledb-postgis:1.7.4-pg11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 30

  geoserver:
    container_name: monitorenv_geoserver
    image: kartoza/geoserver:2.20.2
    environment:
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
    ports:
      - ${GEOSERVER_PORT}:8080
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - geoserver-settings:/settings
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8080/geoserver/index.html || exit 1"]
      interval: 1m30s
      timeout: 1s
      retries: 30

volumes:
  db-data:
    driver: local

  geoserver-data:
    driver: local
  geoserver-settings:
    driver: local
