package fr.gouv.cacem.monitorenv.domain.entities.controlUnit

// Don't forget to mirror any update here in the frontend enum (in both Env and Fish).
enum class ControlUnitResourceType(val label: String) {
    AIRPLANE("Avion"),
    BARGE("Barge"),
    CANOE("Canoë"),
    CAR("Voiture"),
    DRONE("Drône"),
    EQUESTRIAN("Équestre"),
    FAST_BOAT("Vedette"),
    FRIGATE("Frégate"),
    HELICOPTER("Hélicoptère"),
    HYDROGRAPHIC_SHIP("Bâtiment hydrographique"),
    JET_SKI("Jet-ski"),
    KAYAK("Kayak"),
    LIGHT_FAST_BOAT("Vedette légère"),
    MINE_DIVER("Plongeur démineur"),
    MOTORCYCLE("Moto"),
    NET_LIFTER("Remonte-filets"),
    PATROL_BOAT("Patrouilleur"),
    PEDESTRIAN("Piéton"),
    PIROGUE("Pirogue"),
    RESEARCH_SHIP("Navire de recherche"),
    RIGID_HULL("Coque rigide"),
    SEA_SCOOTER("Scooter de mer"),
    SEMI_RIGID("Semi-rigide"),
    SUPPORT_SHIP("Bâtiment de soutien"),
    TRAINING_SHIP("Bâtiment-école"),
    TUGBOAT("Remorqueur"),
    UNKNOWN("Type non renseigné"),
}
