SELECT 
    id,
    url,
    layer_name,
    facade,
    ref_reg,
    edition::timestamp,
    editeur,
    source,
    thematique,
    obs,
    date::timestamp,
    date_fin::timestamp,
    validite,
    tempo,
    type,
    ST_ASTEXT(ST_CurveToLine(geom)) AS wkt,
    resume,
    poly_name,
    plan,
    geom as geometry
FROM prod."REG_ENV_V3"