SELECT
    m.ID_FMC_BC_MISSION AS id,
    CASE
        WHEN typ.LIBELLE_COURT='Au port' THEN 'LAND'
        WHEN typ.LIBELLE_COURT='En mer' THEN 'SEA'
        WHEN typ.LIBELLE_COURT='Aérien' THEN 'AIR'
    END AS mission_type,
    m.TRIGRAMME_UTILISATEUR_SAISIE AS open_by,
    m.OBSERVATIONS as observations_cacem,
    fac.LIBELLE as facade,
    m.DATE_DEBUT_MISSION as start_datetime_utc,
    m.DATE_FIN_MISSION as end_datetime_utc,
    m.TRIGRAMME_UTILISATEUR_CLOTURE AS closed_by,
    'POSEIDON_CACEM' AS mission_source
FROM FMC2.FMC_BC_MISSION m
LEFT JOIN FMC2.FMC_CODE_TYPE_CONTROLE typ
ON m.IDC_FMC_TYPE_MISSION = typ.IDC_FMC_TYPE_CONTROLE
LEFT JOIN FMC2.FMC_CODE_PLAN_FACADE fac
ON m.IDC_FMC_PLAN_FACADE = fac.IDC_FMC_PLAN_FACADE
WHERE m.DATE_DEBUT_MISSION < TO_DATE( '2023-01-01', 'YYYY-MM-DD')