package fr.gouv.cacem.monitorenv.infrastructure.database.model

import jakarta.persistence.Entity
import jakarta.persistence.Table
import java.math.BigDecimal

@Entity
@Table(name = "vessels")
data class VesselModel(
    override val batchId: Int?,
    override val category: String?,
    override val commercialName: String?,
    override val flag: String?,
    override val id: Int,
    override val isBanned: Boolean,
    override val imo: String?,
    override val immatriculation: String?,
    override val leisureType: String?,
    override val length: BigDecimal?,
    override val mmsi: String?,
    override val ownerLastName: String?,
    override val ownerFirstName: String?,
    override val ownerDateOfBirth: String?,
    override val ownerPostalAddress: String?,
    override val ownerPhone: String?,
    override val ownerEmail: String?,
    override val ownerCompanyName: String?,
    override val ownerNationality: String?,
    override val ownerBusinessSegment: String?,
    override val ownerLegalStatus: String?,
    override val ownerStartDate: String?,
    override val portOfRegistry: String?,
    override val professionalType: String?,
    override val rowNumber: Int?,
    override val shipId: Int,
    override val shipName: String?,
    override val status: String?,
    override val umsGrossTonnage: BigDecimal?,
) : BaseVesselModel(
        id = id,
        batchId = batchId,
        shipId = shipId,
        status = status,
        category = category,
        isBanned = isBanned,
        imo = imo,
        mmsi = mmsi,
        immatriculation = immatriculation,
        shipName = shipName,
        flag = flag,
        portOfRegistry = portOfRegistry,
        leisureType = leisureType,
        professionalType = professionalType,
        commercialName = commercialName,
        length = length,
        ownerLastName = ownerLastName,
        ownerFirstName = ownerFirstName,
        ownerDateOfBirth = ownerDateOfBirth,
        ownerPostalAddress = ownerPostalAddress,
        ownerPhone = ownerPhone,
        ownerEmail = ownerEmail,
        ownerCompanyName = ownerCompanyName,
        ownerNationality = ownerNationality,
        ownerBusinessSegment = ownerBusinessSegment,
        ownerLegalStatus = ownerLegalStatus,
        ownerStartDate = ownerStartDate,
        rowNumber = rowNumber,
        umsGrossTonnage = umsGrossTonnage,
    )
