--
-- Data for Name: control_topics; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (1, 'Police des mouillages', 'mouillage individuel', 'mouillage interdit/réglementé par Arrêté PREMAR/DDGAEM');
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (2, 'Police des mouillages', 'mouillage individuel', 'autorisation d’occupation temporaire (AOT) individuelle');
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (3, 'Police des mouillages', 'mouillage individuel', 'autre mouillage ayant un impact sur l’environnement');
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (4, 'Police des mouillages', 'ZMEL', 'x bouées');
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (5, 'Police des mouillages', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (6, 'Rejets illicites', 'carénage sauvage', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (7, 'Rejets illicites', 'jet de déchet', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (8, 'Rejets illicites', 'eau grise/eau noire', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (9, 'Rejets illicites', 'eaux de ballast', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (10, 'Rejets illicites', 'hydrocarbure', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (11, 'Rejets illicites', 'rejets d’immersions/ incinération/exploitation/exploration', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (12, 'Rejets illicites', 'rejets atmosphériques', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (13, 'Rejets illicites', 'avitaillement / soutage', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (14, 'Rejets illicites', 'autre type de rejet', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (15, 'Rejets illicites', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (16, 'Police des espèces protégées et de leurs habitats', 'destruction, capture, arrachage, ...', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (17, 'Police des espèces protégées et de leurs habitats', 'perturbation animaux', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (18, 'Police des espèces protégées et de leurs habitats', 'dérogation espèce protégé', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (19, 'Police des espèces protégées et de leurs habitats', 'détention espèce protégée', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (20, 'Police des espèces protégées et de leurs habitats', 'transport, vente, exportation, …', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (21, 'Police des espèces protégées et de leurs habitats', 'atteinte aux habitats d’espèces protégées', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (22, 'Police des espèces protégées et de leurs habitats', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (23, 'Police des espèces protégées et de leurs habitats', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (24, 'Introduction d’espèce dans le milieu naturel', 'introduction', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (25, 'Introduction d’espèce dans le milieu naturel', 'autorisation d’introduction', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (26, 'Introduction d’espèce dans le milieu naturel', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (27, 'Introduction d’espèce dans le milieu naturel', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (28, 'Atteintes aux biens culturels maritimes', 'déclaration de découverte d’un bien culturel', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (29, 'Atteintes aux biens culturels maritimes', 'atteinte aux biens culturels', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (30, 'Atteintes aux biens culturels maritimes', 'prospection, sondage, prélèvement, fouille, déplacement d’un bien culture', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (31, 'Atteintes aux biens culturels maritimes', 'aliénation ou acquisition', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (32, 'Atteintes aux biens culturels maritimes', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (33, 'Atteintes aux biens culturels maritimes', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (34, 'Police des épaves', 'découverte d’une épave maritime', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (35, 'Police des épaves', 'recel ou détournement d’une épave maritime', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (36, 'Police des épaves', 'épave / navire abandonné', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (37, 'Police des épaves', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (38, 'Police des épaves', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (39, 'Activités et manifestations soumises à évaluation d’incidence Natura 2000', 'document incidences Natura 2000', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (40, 'Activités et manifestations soumises à évaluation d’incidence Natura 2001', 'prescriptions Natura 2000', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (41, 'Activités et manifestations soumises à évaluation d’incidence Natura 2002', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (42, 'Activités et manifestations soumises à évaluation d’incidence Natura 2003', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (43, 'Domanialité publique dont circulation', 'circulation/stationnement de VTM sur le DPM', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (44, 'Domanialité publique dont circulation', 'dérogation/autorisation', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (45, 'Domanialité publique dont circulation', 'balisage', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (46, 'Domanialité publique dont circulation', 'prélèvement de sable ou autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (47, 'Domanialité publique dont circulation', 'dégradation du DPM', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (48, 'Domanialité publique dont circulation', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (49, 'Domanialité publique dont circulation', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (50, 'Police des activités de cultures marines', 'autorisation administrative', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (51, 'Police des activités de cultures marines', 'schéma des structures', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (52, 'Police des activités de cultures marines', 'remise en état', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (53, 'Police des activités de cultures marines', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (54, 'Police des activités de cultures marines', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (55, 'Travaux en milieu marin', 'dragage', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (56, 'Travaux en milieu marin', 'clapage', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (57, 'Travaux en milieu marin', 'extraction de granulats marins', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (58, 'Travaux en milieu marin', 'chantiers portuaires (digue, extension, ...)', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (59, 'Travaux en milieu marin', 'chantiers en mer (éolien, câble, ...)', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (60, 'Travaux en milieu marin', 'suivi d’exploitation', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (61, 'Travaux en milieu marin', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (62, 'Travaux en milieu marin', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (63, 'Pêche à pied', 'loisir', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (64, 'Pêche à pied', 'professionnelle', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (65, 'Pêche à pied', 'braconnage', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (66, 'Pêche à pied', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (67, 'Pêche à pied', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (68, 'Pêche de loisir', 'chasse sous-marine', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (69, 'Pêche de loisir', 'embarquée', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (70, 'Pêche de loisir', 'braconnage', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (71, 'Pêche de loisir', 'autre', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (72, 'Pêche de loisir', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (73, 'Campagnes scientifiques', 'campagne scientifique', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (74, 'Campagnes scientifiques', 'contrôle administratif', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (75, 'Police des parcs nationaux', 'réglementation parc national', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (76, 'Police des réserves naturelles', 'réglementation réserve naturelle', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (77, 'Police des arrêtés de protection', 'réglementation arrêtés de protection', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (78, 'Police du conservatoire du littoral', 'réglementataion du conservatoire du littoral', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (79, 'Police des arrêtés municipaux', 'réglementation arrêté municipal', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (80, 'Police des arrêtés du préfet de région', 'réglementation arrêté du préfet de région', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (81, 'Police des arrêtés du préfet de département', 'réglementation arrêté du préfet de département', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (82, 'Police des arrêtés du préfet maritime', 'réglementation arrêté du préfet maritime', NULL);
INSERT INTO public.control_topics (id, topic_level_1, topic_level_2, topic_level_3) VALUES (83, 'Autres polices', 'réglementation autres polices', NULL);
