CREATE TABLE public.regulatory_areas (
    id serial,
    geom public.geometry(MultiPolygon,4326),
    url character varying,
    layer_name character varying,
    facade character varying,
    ref_reg character varying,
    creation character varying,
    edition_bo character varying,
    edition_cacem character varying,
    editeur character varying,
    source character varying,
    obs character varying,
    thematique character varying,
    date character varying,
    validite character varying,
    date_fin character varying,
    tempo character varying,
    type character varying,
    resume text,
    poly_name text,
    plan text,
    row_hash text
);

