CREATE TABLE VIGILANCE_AREA_PERIOD
(
    ID                       UUID PRIMARY KEY,
    VIGILANCE_AREAS_ID       INT,
    END_DATE_PERIOD          TIMESTAMP,
    ENDING_CONDITION         VIGILANCE_AREA_ENDING_CONDITION,
    ENDING_OCCURRENCE_DATE   TIMESTAMP,
    ENDING_OCCURRENCE_NUMBER INTEGER,
    FREQUENCY                VIGILANCE_AREA_FREQUENCY,
    START_DATE_PERIOD        TIMESTAMP,
    COMPUTED_END_DATE        TIMESTAMP,
    IS_AT_ALL_TIMES          BOOLEAN DEFAULT FALSE,
    IS_CRITICAL              BOOLEAN DEFAULT FALSE
);

INSERT INTO VIGILANCE_AREA_PERIOD (ID, VIGILANCE_AREAS_ID, END_DATE_PERIOD, ENDING_CONDITION, ENDING_OCCURRENCE_DATE,
                                   ENDING_OCCURRENCE_NUMBER, FREQUENCY, START_DATE_PERIOD, COMPUTED_END_DATE,
                                   IS_AT_ALL_TIMES)
SELECT uuid_generate_v4(),
       ID,
       END_DATE_PERIOD,
       ENDING_CONDITION,
       ENDING_OCCURRENCE_DATE,
       ENDING_OCCURRENCE_NUMBER,
       FREQUENCY,
       START_DATE_PERIOD,
       COMPUTED_END_DATE,
       IS_AT_ALL_TIMES
FROM VIGILANCE_AREAS;

ALTER TABLE VIGILANCE_AREAS
    DROP COLUMN END_DATE_PERIOD,
    DROP COLUMN ENDING_CONDITION,
    DROP COLUMN ENDING_OCCURRENCE_DATE,
    DROP COLUMN ENDING_OCCURRENCE_NUMBER,
    DROP COLUMN FREQUENCY,
    DROP COLUMN START_DATE_PERIOD,
    DROP COLUMN COMPUTED_END_DATE,
    DROP COLUMN IS_AT_ALL_TIMES;