import { Layers } from '../../../../src/domain/entities/layers/constants'
import { FAKE_MAPBOX_RESPONSE, PAGE_CENTER_PIXELS } from '../../constants'

context('Search Places', () => {
  beforeEach(() => {
    cy.intercept('GET', 'https://api.mapbox.com/**', FAKE_MAPBOX_RESPONSE)
    cy.visit('/#@-824534.42,6082993.21,8.70')
  })

  it('A user can search a vessel and show its resume when it is selected', () => {
    cy.clickButton('Lieux')
    cy.clickButton('Navires')
    cy.getDataCy('vessel-search-input').type('shipname', { delay: 400 })
    cy.wait(500)
    cy.get('.rs-auto-complete-item').first().click()
    cy.getDataCy('vessel-resume-SHIPNAME 1')
      .should('be.visible')
      .within(() => {
        cy.contains('Latitude')
        cy.contains('47° 38.400′ N')
        cy.contains('Longitude')
        cy.contains('003° 13.176′ W')
        cy.contains('Vitesse')
        cy.contains('20.1 Nds')
        cy.contains('Dernier signal')
        // No assertions for last signal
        cy.contains("Port d'arrivée")
        cy.contains('BRE')
        cy.contains('MMSI')
        cy.contains('123456789')
        cy.contains('IMO')
        cy.contains('IMO1111')
        cy.contains('Immatriculation')
        cy.contains('IMMAT111111')
        cy.contains("Quartier d'immat")
        cy.contains('ALGER')
        cy.contains('Longueur')
        cy.contains('12.12m')
        cy.contains('Pavillon')
        cy.contains('Algérie')
        cy.contains('Catégorie')
        cy.contains('Professionnel')
        cy.contains('Type')
        cy.contains('Porte-conteneur')
        cy.contains('Désignation commerciale')
        cy.contains('COMMERCIAL NAME')
        cy.clickButton('Propriétaire(s)')
        cy.get('header').contains('Informations propriétaire')
        cy.contains('Identité de la personne')
        cy.contains('MICHEL DURAND')
        cy.contains('Coordonnées')
        cy.contains('0102030405')
        cy.contains('email@gmail.com')
        cy.contains('Date de naissance')
        cy.contains('1998-07-12')
        cy.contains('Adresse postale')
        cy.contains('82 STADE DE FRANCE')
        cy.contains('Nationalité')
        cy.contains('France')
        cy.contains('Raison sociale')
        cy.contains('COMPANY NAME 1')
        cy.contains("Secteur d'activité")
        cy.contains('Commerce et réparation de motocycles')
        cy.contains('Statut juridique')
        cy.contains('Société commerciale étrangère immatriculée au RCS')
        cy.contains('Début de la propriété')
        cy.contains('2000-01-01')
      })
    cy.getFeaturesFromLayer(Layers.LAST_POSITIONS.code, PAGE_CENTER_PIXELS).should(features => {
      expect(features).to.have.length(1)
      expect(features?.[0]?.get('shipname')).to.equal('SHIPNAME 1')
    })

    cy.clickButton('Fermer la fiche navire')
    cy.getDataCy('vessel-resume-SHIPNAME 1').should('not.exist')
  })
})
